diff --git a/Makefile b/Makefile
index 5ff0dca..3142721 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
 VERILATOR_FLAGS = \
 	--cc --build --threads 4 --unroll-stmts 999999 -unroll-count 999999 --assert -Wall -Wno-BLKSEQ -Wno-UNUSED \
-	-Wno-PINCONNECTEMPTY -Wno-DECLFILENAME -Wno-ENUMVALUE -Wno-GENUNNAMED -O3 -sv \
+	-Wno-PINCONNECTEMPTY -Wno-DECLFILENAME -Wno-ENUMVALUE -Wno-GENUNNAMED --Wno-PROCASSINIT -O3 -sv \
 	$(VFLAGS) \
 	-CFLAGS "-std=c++17 -march=native" \
 	-LDFLAGS "-ldl" \
@@ -134,6 +134,10 @@ setup:
 prepare_header:
 	python scripts/prepare_header.py obj_dir/\*.h sim/model_headers.h
 
+.PHONY: synth_asic
+synth_asic:
+	/code/hagent/scripts/synth.py --tech-dir /code/workspace/tech --top SoC $(SRC_FILES) $(SLANG_FLAGS) --max-loop-analysis-steps 1024
+
 $(SLANG_HEADER_OUTPUT): src/Config.sv src/Include.sv
 	@if [ -x "`command -v slang-reflect`" ]; then \
 	mkdir -p sim/slang && \
